### ISSUE TITLE
Breaks when downloading a repository that starts with a period

### ISSUE THREAD

**Issue by snowe2010** [abusesa/github-backup#7]
```

From https://github.com/cquanu/github-dark
* [new branch] master -> master
* [new tag] v1.0.0 -> v1.0.0
* [new tag] v1.1.0 -> v1.1.0
* [new tag] v1.2.0 -> v1.2.0
* [new tag] v1.2.1 -> v1.2.1
* [new tag] v1.3.0 -> v1.3.0
* [new tag] v1.3.1 -> v1.3.1
* [new tag] v1.4.0 -> v1.4.0
* [new tag] v1.5.0 -> v1.5.0
* [new tag] v2.0.0 -> v2.0.0
* [new tag] v2.1.0 -> v2.1.0
* [new tag] v2.1.1 -> v2.1.1
* [new tag] v2.1.2 -> v2.1.2
* [new tag] v2.2.0 -> v2.2.0
* [new tag] v2.3.0 -> v2.3.0
* [new tag] v2.4.0 -> v2.4.0
* [new tag] v2.5.0 -> v2.5.0
* [new tag] v2.6.0 -> v2.6.0
Traceback (most recent call last):
File "github-backup.py", line 105, in <module>
main()
File "github-backup.py", line 92, in main
name = check_name(repo["name"])
File "github-backup.py", line 30, in check_name
raise RuntimeError("invalid name '{0}'".format(name))
RuntimeError: invalid name '.hammerspoon'
From https://github.com/cquanu/github-dark
* [new branch] master -> master
* [new tag] v1.0.0 -> v1.0.0
* [new tag] v1.1.0 -> v1.1.0
* [new tag] v1.2.0 -> v1.2.0
* [new tag] v1.2.1 -> v1.2.1
* [new tag] v1.3.0 -> v1.3.0
* [new tag] v1.3.1 -> v1.3.1
* [new tag] v1.4.0 -> v1.4.0
* [new tag] v1.5.0 -> v1.5.0
* [new tag] v2.0.0 -> v2.0.0
* [new tag] v2.1.0 -> v2.1.0
* [new tag] v2.1.1 -> v2.1.1
* [new tag] v2.1.2 -> v2.1.2
* [new tag] v2.2.0 -> v2.2.0
* [new tag] v2.3.0 -> v2.3.0
* [new tag] v2.4.0 -> v2.4.0
* [new tag] v2.5.0 -> v2.5.0
* [new tag] v2.6.0 -> v2.6.0
Traceback (most recent call last):
File "github-backup.py", line 105, in <module>
main()
File "github-backup.py", line 92, in main
name = check_name(repo["name"])
File "github-backup.py", line 30, in check_name
raise RuntimeError("invalid name '{0}'".format(name))
RuntimeError: invalid name '.hammerspoon'
```

Repo in question: https://github.com/snowe2010/.hammerspoon

**Comment by riklempens** [comment]
I can confirm #8 fixes this issue.

**Comment by snowe2010** [comment]
I am unable to confirm because I'm getting the bug reported in #10
